# Site settings
title: Pedro Gomes 
email: pedro.gomes19@ucl.ac.uk
description: Professional webpage of Pedro Gomes
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Pedro Gomes<br/>
    PhD student<br/>
    University College of London

location: >
  University College of London<br/>
  London, United Kingdom

contact: >
    <a href="mailto:pedro.gomes19@ucl.ac.uk" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Pedro via email</a> <br/>
   

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publications
#  - name: talks
#  - name: software
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Gomes
  first_name: [Pedro M.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
